# Snakemake workflow for TNBC Bulk RNA-Seq Analysis
# Author: Suleyman Hajizadeh
# Target Dataset: GSE183947 (SRA: SRR16800543)
# Reference Genome: GRCh38 (GCF_000001405.40)

configfile: "config.yaml"

SAMPLES = [config.get("sample_id", "SRR16800543")]

rule all:
    input:
        "results/fastqc_report.html",
        "results/trimmed_SRR16800543_1.fastq.gz",
        "results/aligned_reads.sorted.bam",
        "results/counts.txt",
        "results/diff_expr_results.csv"

rule download_sra:
    output:
        r1 = temp("reads/{sample}_1.fastq"),
        r2 = temp("reads/{sample}_2.fastq")
    params:
        outdir = "reads"
    shell:
        """
        fasterq-dump --split-files --outdir {params.outdir} {wildcards.sample}
        """

rule fastqc:
    input:
        r1 = "reads/{sample}_1.fastq",
        r2 = "reads/{sample}_2.fastq"
    output:
        html = "results/fastqc_report.html",
        zip = "results/fastqc_report_fastqc.zip"
    params:
        outdir = "results"
    shell:
        """
        fastqc -o {params.outdir} {input.r1} {input.r2}
        mv results/{wildcards.sample}_1_fastqc.html {output.html}
        mv results/{wildcards.sample}_1_fastqc.zip {output.zip}
        """

rule trim_reads:
    input:
        r1 = "reads/{sample}_1.fastq",
        r2 = "reads/{sample}_2.fastq"
    output:
        r1_paired = "results/trimmed_{sample}_1.fastq.gz",
        r1_unpaired = temp("results/unpaired_{sample}_1.fastq.gz"),
        r2_paired = "results/trimmed_{sample}_2.fastq.gz",
        r2_unpaired = temp("results/unpaired_{sample}_2.fastq.gz")
    params:
        adapters = lambda wildcards: config.get("adapters_path", "data/adapters.fa")
    shell:
        """
        trimmomatic PE -phred33 {input.r1} {input.r2} \
            {output.r1_paired} {output.r1_unpaired} \
            {output.r2_paired} {output.r2_unpaired} \
            ILLUMINACLIP:{params.adapters}:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
        """

rule align_hisat2:
    input:
        r1 = "results/trimmed_{sample}_1.fastq.gz",
        r2 = "results/trimmed_{sample}_2.fastq.gz"
    output:
        bam = "results/aligned_reads.sorted.bam"
    params:
        index = lambda wildcards: config.get("reference_index", "data/reference/grch38_index")
    shell:
        """
        hisat2 -x {params.index} -1 {input.r1} -2 {input.r2} | \
        samtools view -S -b - | \
        samtools sort -o {output.bam}
        samtools index {output.bam}
        """

rule count_features:
    input:
        bam = expand("results/aligned_reads.sorted.bam", sample=SAMPLES)
    output:
        counts = "results/counts.txt"
    params:
        gtf = lambda wildcards: config.get("gtf_path", "data/reference/grch38.gtf")
    shell:
        """
        featureCounts -T 4 -p -a {params.gtf} -o {output.counts} {input.bam}
        """

rule run_deseq2:
    input:
        counts = "results/counts.txt"
    output:
        csv = "results/diff_expr_results.csv"
    script:
        "scripts/run_deseq2_analysis.R"
